services:
  - type: web
    name: video-stabilizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Video_Stabilizer_Web.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: prathiksharao
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
